'use client';
/* oxlint-disable jsx-a11y/control-has-associated-label, next/no-html-link-for-pages */

import { useMemo, useState, useSyncExternalStore } from 'react';
import projects from '../canon/projects.json';
import entities from '../canon/presentation_entities.json';
import timeline from '../canon/timeline.json';
import worlds from '../canon/project-worlds.json';
import PlaygroundPanel from '../components/playground/PlaygroundPanel';

type Language = 'pt' | 'en';
const familyGroups = [
  { key: 'ESTER', label: 'IA & IDENTIDADE_', ids: ['ESTER'] },
  { key: 'ONE LIFE / IARA', label: 'AGÊNCIA & VIDA_', ids: ['ONE LIFE / IARA'] },
  { key: 'PAVI EMS', label: 'CARROS & ELETRÔNICA_', ids: ['PAVI EMS'] },
  { key: 'GAMES', label: 'JOGOS & MUNDOS_', ids: ['GAMES'] },
  { key: 'ENGINE / MECHANICAL', label: 'MOTORES & MECÂNICA_', ids: ['ENGINE / MECHANICAL'] },
  { key: 'DOCUMENTARY / ARCHIVE', label: 'ARQUIVO & DOCUMENTOS_', ids: ['DOCUMENTARY / ARCHIVE'] },
  { key: 'CHARACTERS', label: 'PERSONAGENS & DADOS_', ids: ['CHARACTERS'] },
  { key: 'EXPERIMENTS', label: 'EXPERIMENTOS_', ids: ['EXPERIMENTS'] },
];
const t = {
  pt: { nav: ['GAVETAS', 'O QUE SOBROU', 'O QUE SUMIU', 'ARQUEOLOGIA'], kicker: 'ARQUIVO_ASSEMBLY / MESA DE TRABALHO', title: 'Coisas que decidimos', em: 'tentar.', intro: 'Um arquivo de coisas que decidimos tentar. Feito com as sobras: pastas, placas, modelos, cenas, documentos e perguntas que ainda não fecharam.', drawers: 'Abrir as gavetas', survived: 'O que sobrou_', missing: 'O que sumiu_', surprise: 'Me surpreenda_', progress: 'Seu arquivo_', method: 'Como ler isso', archaeology: 'Ver o registro técnico', note: 'A história vive nos objetos. O registro técnico continua disponível quando a brincadeira precisa de precisão.' },
  en: { nav: ['DRAWERS', 'WHAT SURVIVED', 'WHAT DISAPPEARED', 'ARCHAEOLOGY'], kicker: 'ARCHIVE_ASSEMBLY / WORK TABLE', title: 'Things we decided', em: 'to try.', intro: 'An archive of things we decided to try. Made from the remains: folders, boards, models, scenes, documents and questions that never quite closed.', drawers: 'Open the drawers', survived: 'What survived_', missing: 'What disappeared_', surprise: 'Surprise me_', progress: 'Your archive_', method: 'How to read this', archaeology: 'Open the technical record', note: 'The story lives in the objects. The technical record stays available whenever play needs precision.' },
};
const subscribeLocalArchive = (onChange: () => void) => { if (typeof window === 'undefined') return () => {}; window.addEventListener('storage', onChange); window.addEventListener('archive-local-change', onChange); return () => { window.removeEventListener('storage', onChange); window.removeEventListener('archive-local-change', onChange); }; };
const localArchiveValue = (key: string) => typeof window === 'undefined' ? '[]' : window.localStorage.getItem(key) ?? '[]';
const parseLocalArray = (value: string) => { try { const parsed = JSON.parse(value); return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === 'string') : []; } catch { return []; } };

export default function Home() {
  const [language, setLanguage] = useState<Language>('pt');
  const [query, setQuery] = useState('');
  const visited = parseLocalArray(useSyncExternalStore(subscribeLocalArchive, () => localArchiveValue('archive-visited'), () => '[]'));
  const achievements = parseLocalArray(useSyncExternalStore(subscribeLocalArchive, () => localArchiveValue('archive-achievements'), () => '[]'));
  const [emptyClicks, setEmptyClicks] = useState(0);
  const [recordMode, setRecordMode] = useState(false);
  const copy = t[language];
  const unlock = (name: string) => { if (achievements.includes(name)) return; const next = [...achievements, name]; try { localStorage.setItem('archive-achievements', JSON.stringify(next)); window.dispatchEvent(new Event('archive-local-change')); } catch { /* ignore */ } };
  const recordVisit = (id: string) => { const next = Array.from(new Set([...visited, id])); try { localStorage.setItem('archive-visited', JSON.stringify(next)); window.dispatchEvent(new Event('archive-local-change')); } catch { /* ignore */ } if (next.length >= 10) unlock('ARQUEÓLOGO AMADOR_'); if (['pavi-ems-p0', 'pavi-ems-p1', 'pavi-ems-p05x', 'ft300x'].every((item) => next.includes(item))) unlock('OFICINA_'); if (id === 'ai-game-battle') unlock('SEM VENCEDOR_'); };
  const surprise = () => { const options = projects.map((p) => `/projects/${p.id}`).concat(['/artifacts', '/graveyard', '/archaeology']); window.location.href = options[Math.floor(Math.random() * options.length)]; };
  const visible = useMemo(() => projects.filter((p) => !query || `${p.name} ${p.aliases.join(' ')} ${p.short}`.toLowerCase().includes(query.toLowerCase())), [query]);
  const beyond = entities.find((e) => e.entity_id === 'beyond-racing-3d');
  const grave = projects.filter((p) => p.state !== 'FROZEN' || p.build === 'NO' || p.runtime === 'NO' || p.maturity.includes('LOST') || p.maturity.includes('MISSING'));
  return <main className={`living-archive${recordMode ? ' record-mode' : ''}`}>
    <header className="living-topbar"><a className="paper-wordmark" href="#top">ARQUIVO INACABADO<span>_</span></a><nav aria-label="Primary navigation">{copy.nav.map((label, i) => <a href={['#drawers', '#survived', '#missing', '/archaeology'][i]} key={label}>{label}</a>)}</nav><div className="living-tools"><span className="paper-stamp">069 / FROZEN</span><button className="paper-button language-toggle" onClick={() => setLanguage(language === 'pt' ? 'en' : 'pt')} aria-label={language === 'pt' ? 'Switch to English' : 'Mudar para português'}>{language === 'pt' ? 'EN' : 'PT'}</button></div></header>
    <section className="desk-hero" id="top"><div className="desk-note note-coral">{copy.kicker}<br /><b>não jogar fora</b></div><div className="desk-folder"><div className="folder-tab">ARQUIVO_000</div><div className="folder-paper"><div className="eyebrow">{copy.kicker}</div><h1>{copy.title}<br /><em>{copy.em}</em></h1><p>{copy.intro}</p><div className="hero-buttons"><a className="paper-button paper-button-dark" href="#drawers">{copy.drawers} ↘</a><button className="paper-button paper-button-yellow" onClick={surprise}>{copy.surprise} ✦</button></div></div></div><div className="desk-object object-usb"><span>USB_069</span><b>?</b></div><div className="desk-object object-aster">ESTER<br /><small>identity / memory / model</small></div><div className="desk-object object-cad">CAD / STEP / STL<br /><small>ARTEFATO DE REFERÊNCIA</small></div><div className="desk-stamp">PÓS-<br />CONGELAMENTO</div></section>
    <section className="scrap-strip"><span>IA ✦ CARROS ✦ JOGOS ✦ MOTORES ✦ MODELOS ✦ PLACAS ✦ IDEIAS ✦ BUILD PERDIDO ✦ QUASE DEU CERTO ✦</span></section>
    <section className="progress-card"><div><span className="eyebrow">{copy.progress}</span><strong suppressHydrationWarning>{String(visited.length).padStart(2, '0')} / 21 salas visitadas</strong></div><div className="progress-track"><i style={{ width: `${Math.min(100, (visited.length / 21) * 100)}%` }} /></div><button className="paper-button" onClick={() => document.getElementById('drawers')?.scrollIntoView({ behavior: 'smooth' })}>Continuar de onde parei ↗</button><span className="achievement" suppressHydrationWarning>{achievements.length} conquistas locais</span>{achievements.length > 0 && <small className="achievement-list">{achievements.join(' · ')}</small>}</section>
    <section className="drawer-wall" id="drawers"><div className="wall-heading"><div><div className="eyebrow">01 / GAVETAS</div><h2>{copy.drawers}<br /><em>tem uma coisa em cada.</em></h2></div><label className="paper-search">⌕ <input value={query} onChange={(e) => setQuery(e.target.value)} placeholder={language === 'pt' ? 'procurar uma coisa...' : 'look for something...'} /></label></div><div className="drawer-grid">{familyGroups.map((group, index) => { const items = visible.filter((p) => group.ids.includes(p.family)); return <details className={`drawer drawer-${index + 1}`} open={index < 2} key={group.key}><summary><span className="drawer-tab">{String(index + 1).padStart(2, '0')}</span><strong>{group.label}</strong><small>{items.length} objetos · abrir</small></summary><div className="drawer-items">{items.map((project) => { const world = worlds.find((w) => w.entity_id === project.id); return <a className="object-card" href={`/projects/${project.id}`} onClick={() => recordVisit(project.id)} key={project.id}><span className="object-card-meta">{project.latest} / {world?.motif ?? 'archive'}</span><h3>{project.name}<b>↗</b></h3><p>{project.oneLine}</p><span className="object-card-foot">{project.state} · {project.artifact}</span></a>; })}</div></details>; })}</div></section>
    <section className="survived-zone" id="survived"><div className="zone-heading"><div className="eyebrow">02 / {copy.survived}</div><h2>Não é uma coleção de promessas.</h2><p>São os objetos que ainda conseguimos apontar: um source, uma cena, uma placa descrita, um closeout, uma pergunta marcada.</p></div><div className="artifact-table">{projects.slice(0, 6).map((project, i) => <a href={`/projects/${project.id}`} onClick={() => recordVisit(project.id)} key={project.id}><span className="artifact-index">{String(i + 1).padStart(2, '0')}</span><span><b>{project.artifact}</b><small>{project.name}</small></span><i>{project.state}</i></a>)}</div></section>
    {beyond && <section className="lost-envelope" id="missing"><div className="envelope-label">FORA DA CONTAGEM CANÔNICA_</div><div><div className="eyebrow">03 / {copy.missing}</div><h2>Há pastas que continuam vazias.</h2><p>Beyond Racing 3D tem source Unity, prefabs e uma cena preservada, mas não possui build. Não foi apagado nem promovido a projeto 21.</p><button className="paper-button paper-button-dark" onClick={() => { const next = emptyClicks + 1; setEmptyClicks(next); if (next >= 3) unlock('NÃO TINHA NADA AQUI_'); }}>Insistir no envelope ({emptyClicks}/3)</button> <a className="paper-button paper-button-dark" href="/entities/beyond-racing-3d" onClick={() => recordVisit('beyond-racing-3d')}>Abrir envelope ↗</a>{emptyClicks >= 3 && <small className="envelope-reveal">NÃO TINHA NADA AQUI_ — só a evidência de que faltou um build.</small>}</div><div className="envelope-mark">BUILD<br /><span>?</span></div></section>}
    <section className="graveyard-zone"><div className="zone-heading"><div className="eyebrow">04 / CEMITÉRIO</div><h2>O que sumiu<br /><em>também deixa marca.</em></h2><p>O Graveyard guarda finais incompletos sem chamar tudo de fracasso. {grave.length} registros carregam alguma ausência verificável.</p><a className="paper-button paper-button-coral" href="/graveyard" onClick={() => unlock('COVEIRO_')}>Entrar no cemitério ↗</a></div><div className="graveyard-tickets">{grave.slice(0, 4).map((project) => <a href={`/projects/${project.id}`} key={project.id}><span>LOST / {project.latest}</span><strong>{project.name}</strong><small>{project.build === 'NO' ? 'build não preservado' : 'estado incompleto'}</small></a>)}</div></section>
    <section className="record-band"><div><div className="eyebrow">{copy.method}</div><h2>HISTÓRIA_ <em>↔</em> REGISTRO_</h2></div><p>{recordMode ? 'A mesa achatou. Agora você está vendo a camada técnica, sem sair da página.' : copy.note}</p><button className="paper-button paper-button-dark" onClick={() => { setRecordMode((mode) => !mode); unlock('FOI LONGE DEMAIS_'); }}>{recordMode ? 'Voltar à história ↗' : copy.archaeology} </button></section>
    <section className="timeline-scraps"><div className="eyebrow">05 / FRAGMENTOS DE TEMPO</div><div className="scrap-grid">{timeline.slice(0, 5).map((event) => <article key={`${event.kind}-${event.label}`}><time>{event.date}</time><b>{event.kind}</b><p>{event.label}</p><small>{event.confidence} confidence</small></article>)}</div></section>
    <PlaygroundPanel visited={visited} recordVisit={recordVisit} />
    <footer className="living-footer"><span>ARQUIVO INACABADO_ / feito de coisas que sobraram</span><span>CANON: 20 · PRESENTATION: 22 · ROOMS: 21</span><a href="/about">sobre o arquivo ↗</a></footer>
  </main>;
}
