'use client';

import { useEffect, useMemo, useState } from 'react';

type Props = { visited: string[]; recordVisit: (id: string) => void };
type Tool = 'battle' | 'prove' | 'pavi' | 'model' | 'ester' | 'emoji' | 'rotary' | 'beyond' | 'terminal';

const achievements = [
  ['ARQUEÓLOGO AMADOR_', 'visitou dez salas'],
  ['ABRIU TODAS AS GAVETAS_', 'explorou todas as famílias'],
  ['COVEIRO_', 'procurou onde faltava coisa'],
  ['FOI LONGE DEMAIS_', 'chegou ao registro 069'],
  ['NÃO TINHA NADA AQUI_', 'insistiu no artefato perdido'],
  ['MECÂNICO DIGITAL_', 'visitou a família PAVI'],
  ['SEM VENCEDOR_', 'encontrou o fim não resolvido da Arena'],
  ['21 SALAS_', 'visitou todas as salas'],
];

export default function PlaygroundPanel({ visited, recordVisit }: Props) {
  const [serious, setSerious] = useState(false);
  const [tool, setTool] = useState<Tool>('battle');
  const [revealed, setRevealed] = useState<string[]>([]);
  const [graveClicks, setGraveClicks] = useState(0);
  const [terminal, setTerminal] = useState('');
  const [terminalOutput, setTerminalOutput] = useState('');
  const [proveChoice, setProveChoice] = useState('');
  const [rotarySeal, setRotarySeal] = useState('');
  const [emojiTick, setEmojiTick] = useState(0);

  useEffect(() => { try { setSerious(localStorage.getItem('archive-serious') === '1'); } catch { /* local only */ } }, []);
  useEffect(() => { try { localStorage.setItem('archive-last-route', window.location.pathname); } catch { /* local only */ } }, []);

  const unlock = (name: string) => { if (!revealed.includes(name)) setRevealed((current) => [...current, name]); };
  const toggleSerious = () => { const next = !serious; setSerious(next); try { localStorage.setItem('archive-serious', next ? '1' : '0'); } catch { /* local only */ } };
  const paviVisited = useMemo(() => ['pavi-ems-p0', 'pavi-ems-p1', 'pavi-ems-p05x', 'ft300x'].filter((id) => visited.includes(id)).length, [visited]);
  const allFamilies = visited.length >= 20;
  const showTool = (next: Tool) => { setTool(next); if (next === 'battle') unlock('SEM VENCEDOR_'); };
  const runTerminal = () => { const command = terminal.trim().toLowerCase(); const output: Record<string, string> = { help: 'projects · lost · random · graveyard · ester · pavi · battle · 069 · clear · exit', projects: '20 canônicos / 22 entidades / 21 salas', lost: 'found: several things\nrecovered: fewer than we would like', '069': 'ARQUEOLOGY 069 — FROZEN', graveyard: '8 registros com ausência verificável', battle: 'BATTLE 1 — RECORD NOT RECOVERED', ester: 'ASTER / ESTER / MODEL / PERSON / RUNTIME — não é tudo um programa só', pavi: 'PAVI: base existente → ecossistema em volta', random: 'A gaveta certa é sempre a próxima.', clear: '', exit: 'a mesa continua aqui.' }; setTerminalOutput(output[command] ?? `comando desconhecido: ${command || '(vazio)'}`); if (command === '069') unlock('FOI LONGE DEMAIS_'); };

  if (serious) return <section className="playground serious-playground" aria-labelledby="playground-title"><div className="playground-head"><div><div className="eyebrow">CAMADA OPCIONAL / MODO SÉRIO_</div><h2 id="playground-title">O registro permanece.</h2><p>Conquistas, piadas, sorteios e brinquedos estão pausados. A navegação e os fatos canônicos continuam disponíveis.</p></div><button className="paper-button" onClick={toggleSerious}>Ativar playground</button></div><div className="serious-facts"><span>CANONICAL PROJECTS <b>20</b></span><span>PRESENTATION ENTITIES <b>22</b></span><span>DEDICATED PAGES <b>21</b></span></div></section>;

  return <section className="playground" aria-labelledby="playground-title"><div className="playground-head"><div><div className="eyebrow">CAMADA DE CURIOSIDADE / PLAYGROUND_</div><h2 id="playground-title">Puxe uma coisa.</h2><p>Brinquedos pequenos, derivados do arquivo. Tudo aqui é uma explicação interativa — não um runtime histórico.</p></div><button className="paper-button" onClick={toggleSerious}>Modo sério_</button></div><div className="playground-tools" role="tablist" aria-label="Experiências do arquivo">{([['battle', 'THE ARENA_'], ['prove', 'PROVE IT_'], ['pavi', 'ROTEIE UM SINAL_'], ['model', 'PROMOTE OR REJECT_'], ['ester', 'UNTANGLE ESTER_'], ['emoji', 'ARCHIVE SIMULATION_'], ['rotary', 'SEAL IT_'], ['beyond', 'CADÊ O JOGO?_'], ['terminal', 'TERMINAL_']] as [Tool, string][]).map(([id, label]) => <button className={tool === id ? 'active' : ''} role="tab" aria-selected={tool === id} onClick={() => showTool(id)} key={id}>{label}</button>)}</div><div className="playground-stage" role="tabpanel">
    {tool === 'battle' && <div><span className="playground-label">AI GAME BATTLE / RECORD INCOMPLETE_</span><h3>THE ARENA_</h3><p>BATTLE 2 → BATTLE 3 → BATTLE 4 → BATTLE 5 → SOVEREIGN WARS</p><div className="arena-cards">{['BATTLE 1', 'BATTLE 2', 'BATTLE 3', 'BATTLE 4', 'BATTLE 5'].map((round, i) => <button onClick={() => { unlock('SEM VENCEDOR_'); setRevealed((current) => current); }} key={round}><b>{round}</b><small>{i === 0 ? 'NOT RECOVERED' : 'preserved record'}</small></button>)}</div><div className="winner-slot" onClick={() => unlock('SEM VENCEDOR_')} role="button" tabIndex={0}>WINNER_ <strong>[ RECORD LOST / UNRESOLVED ]</strong></div></div>}
    {tool === 'prove' && <div><span className="playground-label">INTERACTIVE EXPLANATION_</span><h3>PROVE IT_</h3><p>Claim: uma ECU tem schematic capturado, mas não há prova de PCB implementada.</p><div className="evidence-cards"><span>SCHEMATIC FILE EXISTS</span><span>PCB FILE = EMPTY SHELL</span><span>NO MANUFACTURING RECEIPT</span></div><div className="choice-row">{['A) hardware existed', 'B) PCB implemented', 'C) schematic exists; PCB unconfirmed'].map((choice) => <button className={proveChoice === choice ? 'selected' : ''} onClick={() => setProveChoice(choice)} key={choice}>{choice}</button>)}</div>{proveChoice && <p className={proveChoice.startsWith('C') ? 'correct' : 'explain'}>{proveChoice.startsWith('C') ? 'CORRETO_: evidência de schematic não sobe sozinha para PCB ou hardware.' : 'Ainda não_: presença de um artefato não comprova a etapa seguinte.'}</p>}</div>}
    {tool === 'pavi' && <div><span className="playground-label">ARCHIVE VISUALIZATION_</span><h3>ROTEIE UM SINAL_</h3><p>Um mapa simplificado de evidência, não instrução de montagem.</p><div className="signal-chain"><span>SENSOR</span><i>→</i><span>CONDITIONING</span><i>→</i><span>MCU</span><i>→</i><span>LOGIC</span><i>→</i><span>OUTPUT</span></div><button className="paper-button paper-button-coral" onClick={() => unlock('MECÂNICO DIGITAL_')}>Marcar percurso</button><small>{paviVisited}/4 salas PAVI visitadas</small></div>}
    {tool === 'model' && <div><span className="playground-label">HISTORICAL EVALUATION PATH_</span><h3>PROMOTE OR REJECT_</h3><p>BASE MODEL → TRAINING → ADAPTER → EVALUATION</p><div className="model-result"><b>72.92% PARTIAL</b><b>0 / 16 STRICT</b><span>NO SAFE WINNER</span></div><div className="choice-row"><button onClick={() => setProveChoice('reject')}>REJECT_</button><button onClick={() => setProveChoice('promote')}>PROMOTE_</button></div>{proveChoice && <p className="explain">A decisão arquivada permanece: <b>NO SAFE WINNER</b>. Uma interação não muda a história.</p>}</div>}
    {tool === 'ester' && <div><span className="playground-label">RELATION MAP / NO FALSE LINEAGE_</span><h3>UNTANGLE ESTER_</h3><div className="relation-map">{['ASTER', 'ESTER', 'MODELPERSON', 'PORTABLE CORE', 'MIND ORB', 'ONE LIFE / IARA'].map((node) => <button onClick={() => unlock('IDENTIDADE EM CRISE_')} key={node}>{node}</button>)}</div><p>Explore as relações sem transformar referências, componentes e projetos paralelos em um único programa.</p></div>}
    {tool === 'emoji' && <div><span className="playground-label">PRESENT-DAY SIMULATION_</span><h3>ARCHIVE SIMULATION_</h3><p>Não é runtime histórico. É uma micro-simulação limitada e pausável de agentes EmojiLife.</p><div className="emoji-world" aria-live="polite"><span style={{ transform: `translate(${(emojiTick * 23) % 130}px, ${(emojiTick * 11) % 38}px)` }}>🙂</span><span style={{ transform: `translate(${(emojiTick * 17) % 125}px, ${(emojiTick * 19) % 42}px)` }}>🧑‍🔧</span></div><button className="paper-button" onClick={() => setEmojiTick((tick) => tick + 1)}>Avançar um evento ({emojiTick})</button></div>}
    {tool === 'rotary' && <div><span className="playground-label">ARCHIVE VISUALIZATION_</span><h3>SEAL IT_</h3><div className="rotor-diagram"><div className="rotor">△</div><div className="seal apex">APEX SEAL</div><div className="seal side">SIDE SEAL</div></div><div className="choice-row"><button className={rotarySeal === 'APEX' ? 'selected' : ''} onClick={() => { setRotarySeal('APEX'); unlock('SELO ENCONTRADO_'); }}>Identificar apex</button><button className={rotarySeal === 'SIDE' ? 'selected' : ''} onClick={() => { setRotarySeal('SIDE'); unlock('SELO ENCONTRADO_'); }}>Identificar side</button></div><p>Visualização didática; não representa uma geometria final recuperada.</p></div>}
    {tool === 'beyond' && <div><span className="playground-label">BEYOND POWERS / BOUNDED MYSTERY_</span><h3>CADÊ O JOGO?_</h3><div className="mystery-list"><span>roadmap — documented</span><span>Alpha Jogável — reference</span><span>SC_TESTCITY — missing</span><span>build — not recovered</span></div><button className="paper-button paper-button-yellow" onClick={() => unlock('NÃO TINHA NADA AQUI_')}>Procurar mais fundo</button><p>DOCUMENTED_ YES / RECOVERED PLAYABLE GAME_ NO</p></div>}
    {tool === 'terminal' && <div><span className="playground-label">FICTIONAL ARCHIVE TERMINAL_</span><h3>ARQUIVO_SHELL_</h3><label className="terminal-input">&gt; <input value={terminal} onChange={(event) => setTerminal(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') runTerminal(); }} placeholder="help" aria-label="Comando do terminal" /></label><button className="paper-button" onClick={runTerminal}>executar</button><pre>{terminalOutput || 'digite help. não há acesso ao filesystem.'}</pre></div>}
  </div><div className="playground-bottom"><div><b>SEU ARQUIVO_</b><span suppressHydrationWarning>{String(visited.length).padStart(2, '0')} salas visitadas · {revealed.length} segredos desta sessão</span></div><div className="achievement-strip" aria-live="polite">{revealed.length ? `ACHIEVEMENT UNLOCKED_ ${revealed[revealed.length - 1]}` : 'há uma coisa estranha em algum lugar.'}</div></div><div className="graveyard-mini"><b>GRAVEYARD_</b><span>pastas mortas, envelopes vazios e resultados não resolvidos.</span><button onClick={() => { const next = graveClicks + 1; setGraveClicks(next); if (next >= 3) unlock('NÃO TINHA NADA AQUI_'); }}>Inspecionar pasta perdida ({graveClicks}/3)</button>{graveClicks >= 3 && <em>EU TAMBÉM QUERIA QUE TIVESSE ALGUMA COISA AQUI_</em>}</div>{allFamilies && <div className="secret-room">CAIXA SEM ETIQUETA_ — bônus desbloqueado: o arquivo tem 20 projetos, mas nunca teve uma vida simples.</div>}</section>;
}
