import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (name) => JSON.parse(fs.readFileSync(path.join(root, "canon", name), "utf8"));
const projects = read("projects.json");
const entities = read("presentation_entities.json");
const timeline = read("timeline.json");
const relations = read("relations.json");
const artifacts = read("artifacts.json");
const badges = read("badges.json");
const projectIds = new Set(projects.map((item) => item.id));
const entityIds = new Set(entities.map((item) => item.entity_id));
const knownIds = new Set([...projectIds, ...entityIds]);
const errors = [];
const assert = (condition, message) => { if (!condition) errors.push(message); };
const unique = (values) => new Set(values).size === values.length;
assert(projects.length === 20, `canonical project count is ${projects.length}, expected 20`);
assert(entities.length === 22, `presentation entity count is ${entities.length}, expected 22`);
assert(entities.filter((item) => item.count_as_canonical_project && item.entity_type === "CANONICAL_PROJECT").length === 20, "canonical presentation entity count mismatch");
assert(unique(projects.map((item) => item.id)), "duplicate canonical project id");
assert(unique(entities.map((item) => item.entity_id)), "duplicate presentation entity id");
const beyond = entities.find((item) => item.entity_id === "beyond-racing-3d");
assert(Boolean(beyond), "Beyond Racing entity missing");
assert(beyond?.canonical_project_id === null && beyond?.count_as_canonical_project === false && beyond?.dedicated_page === true, "Beyond Racing reconciliation invariant failed");
for (const event of timeline) assert(!event.project || knownIds.has(event.project), `orphan timeline owner: ${event.project}`);
for (const relation of relations) assert(knownIds.has(relation.from) && knownIds.has(relation.to), `orphan relation: ${relation.from} -> ${relation.to}`);
for (const artifact of artifacts) assert(!artifact.projectId || projectIds.has(artifact.projectId), `orphan artifact project: ${artifact.projectId}`);
assert(Object.keys(badges).length > 0, "badge vocabulary unreadable");
const result = { valid: errors.length === 0, canonicalProjectCount: projects.length, presentationEntityCount: entities.length, dedicatedPageCount: projects.length + entities.filter((item) => item.dedicated_page && !item.count_as_canonical_project).length, errors };
console.log(JSON.stringify(result, null, 2));
if (errors.length) process.exitCode = 1;
